<?php $id_plan = $plan['id_plan']; ?>
<div class='table__div-plan draggable'
     id='planDiv_<?php echo $id_plan; ?>'
     onclick='openPlanWidgets(event);'
     onmouseover="onPlanMouseOver(event);"
     onmouseout="onPlanMouseOut(event);"><?php echo $plan['text_of_plan'] ?><input type='button'
           id='planBtnDel2_<?php echo $id_plan; ?>'
           name='planBtnDel2_<?php echo $id_plan; ?>'
           class='table__small-buttons'
           value=''
           title='Удалить'
           onclick="deleteButtonPressed(event);"
           style="right: 0px; background-image: url('../../assets/images/cross.svg');"></div>
<div class='table__hidden-div-plan'
     id='planHiddenDiv_<?php echo $id_plan; ?>'
     name='planHiddenDiv_<?php echo $id_plan; ?>'>
    <input type='text'
           id='planEditText_<?php echo $id_plan; ?>'
           name='planEditText_<?php echo $id_plan; ?>'
           class='table__textedit-plan'
           onkeyup="KeyPressInPlansEditItem('edit', event);"
           autocomplete='off'>
    <input type='button'
           id='planBtnOk_<?php echo $id_plan; ?>'
           name='planBtnOk_<?php echo $id_plan; ?>'
           class='table__small-buttons'
           value=''
           title='Изменить'
           onclick="ajaxSavePlan('<?php echo $id_plan; ?>');"
           style="right: 32px; background-image: url('../../assets/images/save.svg');">
    <input type='button'
           id='planBtnDel_<?php echo $id_plan; ?>'
           name='planBtnDel_<?php echo $id_plan; ?>'
           class='table__small-buttons'
           value=''
           title='Удалить'
           onclick="ajaxDeletePlan('<?php echo $id_plan; ?>');"
           style="right: 16px; background-image: url('../../assets/images/trash.svg');">
    <input type='reset'
           id='planBtnCancel_<?php echo $id_plan; ?>'
           name='planBtnCancel_<?php echo $id_plan; ?>'
           class='table__small-buttons'
           value=''
           title='Отменить'
           onclick='hidePlanWidgets(<?php echo $id_plan; ?>)'
           style="right: 0px; background-image: url('../../assets/images/block.svg');">
</div>
